# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateField(auto_now=True)),
                ('dni_representante', models.CharField(blank=True, max_length=8, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'permissions': (('list_asistencia', 'Can list categoria'), ('get_asistencia', 'Can get asistencia')),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateField(auto_now=True)),
                ('monto', models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50')], max_length=2)),
                ('num_inasistencias', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='socio_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.SocioLote'),
        ),
    ]
