# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
        ('cobranza', '0001_initial'),
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_recibo', models.CharField(max_length=50)),
                ('validacion', models.BooleanField(default=False)),
                ('inasistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='ValidarPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_deposito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_deposito', models.DateField()),
                ('numero_operacion', models.CharField(max_length=50)),
                ('imagen_voucher', models.ImageField(blank=True, upload_to='')),
                ('cuenta_banco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.CuentaBanco')),
                ('cuota_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.CuotaSocio')),
            ],
            options={
                'verbose_name': 'ValidarPago',
                'verbose_name_plural': 'ValidarPagos',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.Periodo'),
        ),
    ]
